# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Something new every day
email: 
description: > # this means to ignore newlines until "baseurl:"
  I'm interested in lot of things, however will put only useful 
  information about technologies and software development
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yccypuuck.github.io" # the base hostname & protocol for your site
twitter_username: lenorke
github_username:  yccypuuck

# Build settings
markdown: kramdown
